package com.example.mad_ind05_inman_joshua

object StateDataModel {
    val stateList = listOf<State>(
        State("Alabama", "Yellowhammer State", "50,645", "al_flag", "al_map"),
        State("Alaska ","The Last Frontier", "570,641", "ak_flag", "ak_map"),
        State("Arizona","Grand Canyon State", "113,594", "az_flag", "az_map"),
        State("Arkansas","Natural State", "52,035", "ar_flag", "ar_map"),
        State("California","Golden State", "155,779", "ca_flag", "ca_map"),
        State("Colorado","Centennial State", "103,642", "co_flag", "co_map"),
        State("Connecticut","Constitution State", "4,842", "ct_flag", "ct_map"),
        State("Delaware","First State", "1,949", "de_flag", "de_map"),
        State("Florida","Sunshine State", "53,625", "fl_flag", "fl_map"),
        State("Georgia","Peach State", "57,513", "ga_flag", "ga_map"),
        State("Hawaii","Aloha State", "6,423", "hi_flag", "hi_map"),
        State("Idaho","Gem State", "82,643", "id_flag", "id_map"),
        State("Illinois","Prairie State", "55,519", "il_flag", "il_map"),
        State("Indiana","Hoosier State", "35,826", "in_flag", "in_map"),
        State("Iowa","Hawkeye State", "55,857", "ia_flag", "ia_map"),
        State("Kansas","Sunflower State", "81,759", "ks_flag", "ks_map"),
        State("Kentucky","Bluegrass State", "39,486", "ky_flag", "ky_map"),
        State("Louisiana","Pelican State", "43,204", "la_flag", "la_map"),
        State("Maine","Pine Tree State", "30,843", "me_flag", "me_map"),
        State("Maryland","Old Line State", "9,707", "md_flag", "md_map"),
        State("Massachusetts","Bay State", "7,800", "ma_flag", "ma_map"),
        State("Michigan","Great Lake State", "56,539", "mi_flag", "mi_map"),
        State("Minnesota","Land of 10,000 Lakes", "79,627", "mn_flag", "mn_map"),
        State("Mississippi","Magnolia State", "56,924", "ms_flag", "ms_map"),
        State("Missouri","Show Me State", "68,742", "mo_flag", "mo_map"),
        State("Montana","Treasure State", "145,546", "mt_flag", "mt_map"),
        State("Nebraska","Cornhusker State", "76,824", "ne_flag", "ne_map"),
        State("Nevada","Silver State", "109,781", "nv_flag", "nv_map"),
        State("New Hampshire","Granite State", "8,953", "nh_flag", "nh_map"),
        State("New Jersey","Garden State", "7,354", "nj_flag", "nj_map"),
        State("New Mexico","The Land of Enchantment", "121,298", "nm_flag", "nm_map"),
        State("New York","Empire State", "47,126", "ny_flag", "ny_map"),
        State("North Carolina","Tar Heel State", "48,618", "nc_flag", "nc_map"),
        State("North Dakota","Sioux State", "69,001", "nd_flag", "nd_map"),
        State("Ohio","Buckeye State", "40,861", "oh_flag", "oh_map"),
        State("Oklahoma","Sooner State", "68,595", "ok_flag", "ok_map"),
        State("Oregon","Beaver State", "95,988", "or_flag", "or_map"),
        State("Pennsylvania","Keystone State", "44,743", "pn_flag", "pn_map"),
        State("Rhode Island","Ocean State", "1,034", "ri_flag", "ri_map"),
        State("South Carolina","Palmetto State", "30,061", "sc_flag", "sc_map"),
        State("South Dakota","The Mount Rushmore State", "75,811", "sd_flag", "sd_map"),
        State("Tennessee","Volunteer State", "41,235", "tn_flag", "tn_map"),
        State("Texas","Lone Star State", "261,232", "tx_flag", "tx_map"),
        State("Utah","Beehive State", "82,170", "ut_flag", "ut_map"),
        State("Vermont","Green Mountain State", "9,217", "vt_flag", "vt_map"),
        State("Virginia","The Old Dominion State", "39,490", "va_flag", "va_map"),
        State("Washington","Evergreen State", "66,456", "wa_flag", "wa_map"),
        State("West Virginia","Mountain State", "24,038", "wv_flag", "wv_map"),
        State("Wisconsin","Badger State", "54,158", "wi_flag", "wi_map"),
        State("Wyoming","Equality State", "97,093", "wy_flag", "wy_map")
    )
}