package com.example.mad_ind05_inman_joshua

object StateDataModel {
    val stateList = listOf<State>(
        State("Alabama", "Yellowhammer State", "50,645"),
        State("Alaska ","The Last Frontier", "570,641"),
        State("Arizona","Grand Canyon State", "113,594"),
        State("Arkansas","Natural State", "52,035"),
        State("California","Golden State", "155,779"),
        State("Colorado","Centennial State", "103,642"),
        State("Connecticut","Constitution State", "4,842"),
        State("Delaware","First State", "1,949"),
        State("Florida","Sunshine State", "53,625"),
        State("Georgia","Peach State", "57,513"),
        State("Hawaii","Aloha State", "6,423"),
        State("Idaho","Gem State", "82,643"),
        State("Illinois","Prairie State", "55,519"),
        State("Indiana","Hoosier State", "35,826"),
        State("Iowa","Hawkeye State", "55,857"),
        State("Kansas","Sunflower State", "81,759"),
        State("Kentucky","Bluegrass State", "39,486"),
        State("Louisiana","Pelican State", "43,204"),
        State("Maine","Pine Tree State", "30,843"),
        State("Maryland","Old Line State", "9,707"),
        State("Massachusetts","Bay State", "7,800"),
        State("Michigan","Great Lake State", "56,539"),
        State("Minnesota","Land of 10,000 Lakes", "79,627"),
        State("Mississippi","Magnolia State", "56,924"),
        State("Missouri","Show Me State", "68,742"),
        State("Montana","Treasure State", "145,546"),
        State("Nebraska","Cornhusker State", "76,824"),
        State("Nevada","Silver State", "109,781"),
        State("New Hampshire","Granite State", "8,953"),
        State("New Jersey","Garden State", "7,354"),
        State("New Mexico","The Land of Enchantment", "121,298"),
        State("New York","Empire State", "47,126"),
        State("North Carolina","Tar Heel State", "48,618"),
        State("North Dakota","Sioux State", "69,001"),
        State("Ohio","Buckeye State", "40,861"),
        State("Oklahoma","Sooner State", "68,595"),
        State("Oregon","Beaver State", "95,988"),
        State("Pennsylvania","Keystone State", "44,743"),
        State("Rhode Island","Ocean State", "1,034"),
        State("South Carolina","Palmetto State", "30,061"),
        State("South Dakota","The Mount Rushmore State", "75,811"),
        State("Tennessee","Volunteer State", "41,235"),
        State("Texas","Lone Star State", "261,232"),
        State("Utah","Beehive State", "82,170"),
        State("Vermont","Green Mountain State", "9,217"),
        State("Virginia","The Old Dominion State", "39,490"),
        State("Washington","Evergreen State", "66,456"),
        State("West Virginia","Mountain State", "24,038"),
        State("Wisconsin","Badger State", "54,158"),
        State("Wyoming","Equality State", "97,093")
    )
}